### ISSUE TITLE
Chore: setup CodeClimate

### ISSUE THREAD

**Issue by nathan-appere** [rubykit/kit#22]
## Todo:
- [x] CodeClimate setup code coverage w. `SimpleCov`
- [x] Rubocop: setup `kit-doc-yard`
- [x] Rubocop: setup `kit-store`
- [x] Rubocop: setup `kit-router`
- [x] Rubocop: setup `kit-engine`
- [x] Rubocop: setup `kit-domain`
- [x] Rubocop: setup `kit-error`
- [x] Rubocop: setup `kit-dummy-app-container`
- [x] Rubocop: setup `kit-app-container`
- [x] CodeClimate: setup Rubocop
- [x] Rubocop: setup `top-level`
- [x] Rubocop: setup `kit-organizer`
- [x] Rubocop: setup `kit-pagination`
- [x] Rubocop: setup `kit-api-json-api`
- [x] Reamde: add badges

**Comment by nathan-appere** [comment]
Closed by #72 & #73
