### ISSUE TITLE
Kit::Router

### ISSUE THREAD

**Issue by nathan-appere** [rubykit/kit#33]
## Todo
- [x] Add HTTP support
- [x] Add indirection support
- [ ] Add async support
- [ ] Add ActionCable support
- [ ] Add async mode for all non async endpoints!
- [ ] Add a way to mount default domain route?
