### ISSUE TITLE
Kit::Api::JsonApi - Add pagination links

### ISSUE THREAD

**Issue by nathan-appere** [rubykit/kit#57]
## Abstract

The goal is to provide absolute pagination for the top level collection + every relationship loaded.

We allow filters & pagination data for *any* level of a relationship. This has several implications as:
- JSON:API ensures an object is only sent once
- You can traverse the same relationship at different levels of nesting
So in order to maintain collection ordering, an has-many relationship that is loaded through different paths is prefixed with its full path.

## Todos
- [x] Example implementation of a `Linker`
- [x] Link generation for: `single resources` (top level or has one) & `collections` (top level or has many)
- [x] Export query_params `related_resources` for any link
- [x] Export query_params `filters` for any link
- [x] Export query_params `sort` for any link
- [x] Export query_params `sparse_fieldsets` for any link
- [x] Export query_params `page size` for any link
