### ISSUE TITLE
Kit::Doc - Improve modules groups rendering in sidebar

### ISSUE THREAD

**Issue by nathan-appere** [rubykit/kit#60]
## Abstract
The current rendering of the modules in the sidebar is very difficult to understand, mostly because of the nesting we end up doing for Railties loading.
Adding some modifiers options for module should help a lot.

## Todos
- [ ] Add text modifier in groups
- [ ] Add class modifiers in groups
- [ ] Solve missing namespaces in Yard
