### ISSUE TITLE
Kit::Api::JsonApi - Add endpoints helpers

### ISSUE THREAD

**Issue by nathan-appere** [rubykit/kit#77]
## Todos
- [ ] GET endpoints on resources
- [ ] GET endpoints on relationships
- [ ] POST endpoints on resources
- [ ] POST endpoints on relationships
- [ ] PATCH endpoints on resources
- [ ] PATCH endpoints on relationships
- [ ] DELETE endpoints on resources
- [ ] DELETE endpoints on relationships
