### ISSUE TITLE
Kit::Api::JsonApi - Add support for create / update / delete operations

### ISSUE THREAD

**Issue by nathan-appere** [rubykit/kit#78]
## Todo:
- [x] Add CREATE endpoint
- [x] Add UPDATE endpoint
- [x] Add DELETE endpoint
- [x] Add specs for CREATE endpoint
- [x] Add specs for UPDATE endpoint
- [x] Add specs for DELETE endpoint
- [ ] Add error support
- [ ] Add specs for errors
